### ISSUE TITLE
withCredentials on CD 4.1.0

### ISSUE THREAD

**Issue by aqmnguyen** [movableink/cropduster#21]
By default it's set to true, when making requests it looks to be passing additional headers such as cookie information. 

When we make requests to API's as the header information passes through a cookie we get back a `400 Bad Request`

![screenshot 2018-01-02 14 00 26](https://user-images.githubusercontent.com/17278432/34485963-322ebd70-efc5-11e7-95ee-9476943a99a2.png)

Cookie passed via the header request:

![screenshot 2018-01-02 14 01 32](https://user-images.githubusercontent.com/17278432/34485975-4e6af576-efc5-11e7-9535-0876b4e79965.png)

Would it make sense to have `withCredentials` default to `false` and allow for the option to pass it through as `true`/`false` ? 

i.e `req.withCredentials = options.withCredentials || false;`

**Comment by mnutt** [comment]
The intention with `withCredentials` was actually to authenticate the crop page with sorcerer, I'm looking into if we can have sorcerer and cors-proxy strip off `Cookie` headers before sending but need to verify that no requests are currently using `Cookie` headers. (I don't believe that they are, just because you can't currently construct `Cookie` headers manually)

**Comment by aqmnguyen** [comment]
Yup, pretty certain there aren't any requests sending the `Cookie` header, it's as you say we can't construct the `Cookie` manually and when we even try to force it we get an error from `CD`:

`Refused to set unsafe header "Cookie"`.

**Comment by mnutt** [comment]
This should now be resolved, due to an update to cors-proxy.
